Creates the folder in sikar group, regardless of script execution location

diff --git a/source/create b/source/create
--- a/source/create
+++ b/source/create
@@ -29,9 +29,10 @@ create() {
                 ;;
             *)
                 echo "Invalid option: $1"
-                exit 1
+#                exit 1
                 ;;
         esac
+        shift
     done
 
     # Check if type is missing
@@ -69,11 +70,12 @@ create() {
     esac
 
     if $should_open; then
-      source "$SIKAR_SOURCE_DIR"/open "$CURRENT_DIR/$appName"
+      open -a $JAVA_IDE "$APP_DIR"
     fi
     
     # If it's a Git project, create GitHub repo and push to GitHub
     if $is_git_project; then
+        echo -e "${GREEN}Creating GitHub repo${NC}"
         create_github_repo "$name" "$description"
         push_to_github "$name"
     fi
@@ -85,14 +87,13 @@ create_github_repo() {
     local description="$2"
 
     # Create a new repository via GitHub API
-    response=curl -X POST \
+   curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"name": "'"$repo_name"'", "description": "'"$description"'"}' \
          "https://api.github.com/user/repos"
-
      # Check the exit status of curl
     if [ $? -ne 0 ]; then
-      echo -e "${RED}Failed to create repository: $response ${NC}"
+      echo -e "${RED}Failed to create repository${NC}"
       exit 1
     fi
 
@@ -102,7 +103,7 @@ create_github_repo() {
 # Function to push local project to GitHub
 push_to_github() {
     local repo_name="$1"
-    pushd "$CURRENT_DIR/$appName"
+    pushd "$APP_DIR"
     # Initialize a git repository if not already initialized
     if [[ ! -d .git ]]; then
         git init
@@ -121,25 +122,27 @@ push_to_github() {
 # Function to create a plain Java project structure
 create_plain_java_project() {
     local appName=$1
-    local appDir="$CURRENT_DIR/$appName"
-    mkdir -p "$appDir"
+    APP_DIR="$SIKAR_DIR/Java/$appName"
+    mkdir -p "$APP_DIR"
 
     echo "Creating Plain Java project structure for $appName..."
 
-    cp -R "$SIKAR_SYSTEM_DIR"/templates/javaApplication/* "$appDir"
+    cp -R "$SIKAR_SYSTEM_DIR"/templates/javaApplication/* "$APP_DIR"
+
+    sed -i '' -e "s/{project_name}/$appName/g" "$APP_DIR"/pom.sikar
 }
 
 # Function to create a Sikar Boot project structure
 create_sikar_boot_project() {
     local appName=$1
-    local appDir="$CURRENT_DIR/$appName"
-    mkdir -p "$appDir"
+    APP_DIR="$SIKAR_DIR/Boot/$appName"
+    mkdir -p "$APP_DIR"
 
     echo "Creating Sikar Boot project structure for $appName... in $SIKAR_SYSTEM_DIR"
 
-    cp -R "$SIKAR_SYSTEM_DIR"/templates/sikarBootApplication/* "$appDir"
+    cp -R "$SIKAR_SYSTEM_DIR"/templates/sikarBootApplication/* "$APP_DIR"
 
-    sed -i '' -e "s/{project_name}/$appName/g" "$appDir"/pom.sikar.sh
+    sed -i '' -e "s/{project_name}/$appName/g" "$APP_DIR"/pom.sikar
 }
 
 create "$@"
