updates create and deleteRepo

diff --git a/source/create b/source/create
--- a/source/create
+++ b/source/create
@@ -1,13 +1,5 @@
 #!/bin/bash
-# Function to create a new project
 
-# Get the current working directory
-#current_dir="$(pwd)"
-# Load configuration from application.properties
-#source "$current_dir/pom.sikarXml"
-
-#include github repo creation as well
-# parse the arguments and use it if provided
 source "$SIKAR_SYSTEM_DIR/ignore/gitCredentials"
 
 create() {
@@ -15,6 +7,7 @@ create() {
     local type=""
     local description=""
     local is_git_project=false
+    local should_open=false
 
     # Parse command-line options
     while [[ $# -gt 0 ]]; do
@@ -31,16 +24,14 @@ create() {
             --git)
                 is_git_project=true
                 ;;
+            --open)
+                should_open=true
+                ;;
             *)
                 echo "Invalid option: $1"
                 exit 1
                 ;;
         esac
-        echo "before shift"
-        echo "$@"
-        shift
-        echo "after shift"
-        echo "$@"
     done
 
     # Check if type is missing
@@ -76,6 +67,10 @@ create() {
           exit 1
           ;;
     esac
+
+    if $should_open; then
+      source "$SIKAR_SOURCE_DIR"/open "$CURRENT_DIR/$appName"
+    fi
     
     # If it's a Git project, create GitHub repo and push to GitHub
     if $is_git_project; then
@@ -90,16 +85,24 @@ create_github_repo() {
     local description="$2"
 
     # Create a new repository via GitHub API
-    curl -X POST \
+    response=curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"name": "'"$repo_name"'", "description": "'"$description"'"}' \
          "https://api.github.com/user/repos"
+
+     # Check the exit status of curl
+    if [ $? -ne 0 ]; then
+      echo -e "${RED}Failed to create repository: $response ${NC}"
+      exit 1
+    fi
+
+    echo -e "${GREEN}git repo created${NC}"
 }
 
 # Function to push local project to GitHub
 push_to_github() {
     local repo_name="$1"
-    pushd "$(pwd)/$appName"
+    pushd "$CURRENT_DIR/$appName"
     # Initialize a git repository if not already initialized
     if [[ ! -d .git ]]; then
         git init
@@ -111,13 +114,14 @@ push_to_github() {
     git remote add origin "git@github.com:$GITHUB_USERNAME/$repo_name.git"
     # Push code to GitHub
     git push -u origin main
+    echo -e "${GREEN}Initial commit pushed${NC}"
     popd
 }
 
 # Function to create a plain Java project structure
 create_plain_java_project() {
     local appName=$1
-    local appDir="$(pwd)/$appName"
+    local appDir="$CURRENT_DIR/$appName"
     mkdir -p "$appDir"
 
     echo "Creating Plain Java project structure for $appName..."
@@ -128,7 +132,7 @@ create_plain_java_project() {
 # Function to create a Sikar Boot project structure
 create_sikar_boot_project() {
     local appName=$1
-    local appDir="$(pwd)/$appName"
+    local appDir="$CURRENT_DIR/$appName"
     mkdir -p "$appDir"
 
     echo "Creating Sikar Boot project structure for $appName... in $SIKAR_SYSTEM_DIR"
diff --git a/source/deleteRepo b/source/deleteRepo
--- a/source/deleteRepo
+++ b/source/deleteRepo
@@ -78,14 +78,18 @@ delete_project_repo_from_remote() {
     local repo_name="$1"
 
     read -p "Are you sure you want to delete this repository from remote? (y/n): " confirm
-      if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
-        curl -X DELETE \
-                 -H "Authorization: token $GITHUB_TOKEN" \
-                 "https://api.github.com/repos/$GITHUB_USERNAME/$repo_name"
-        echo "deleted from remote"
-      else
-        echo "Operation aborted."
-        exit 0
+    if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
+      curl -X POST \
+           -H "Authorization: token $GITHUB_TOKEN" \
+           "https://api.github.com/repos/$GITHUB_USERNAME/$repo_name"
+      if [ $? -ne 0 ]; then
+          echo -e "${RED}delete not success"
+          exit 1
+      fi
+      echo "deleted from remote"
+    else
+      echo "Operation aborted."
+      exit 0
     fi
 }
 
